name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Install pgvector dependency
      run: |
        sudo apt-get update
        sudo apt-get install -y postgresql-client

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    # Uncomment this if you add tests to your project
    # - name: Test
    #   run: dotnet test --no-build --verbosity normal

    - name: Publish
      run: dotnet publish -c Release -o publish

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: webapp
        path: publish/
